region: us-east-1
metrics:
  - aws_namespace: AWS/Lambda
    aws_metric_name: Duration
    aws_dimensions: [FunctionName]
    aws_statistics: [Average, p95, p99]
  - aws_namespace: AWS/Lambda
    aws_metric_name: Errors
    aws_dimensions: [FunctionName]
    aws_statistics: [Sum]
  - aws_namespace: AWS/ApiGateway
    aws_metric_name: 5XXError
    aws_dimensions: [ApiId]
    aws_statistics: [Sum]
  - aws_namespace: AWS/ApiGateway
    aws_metric_name: Latency
    aws_dimensions: [ApiId]
    aws_statistics: [Average, p95]
