version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "backend"
    open-pull-requests-limit: 10
    rebase-strategy: auto
    security-updates: true
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "frontend"
    open-pull-requests-limit: 10
    rebase-strategy: auto
    security-updates: true
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "ci"
    open-pull-requests-limit: 10
    rebase-strategy: auto
