import type { LucideIcon } from "lucide-react";
import {
  Activity,
  Bell,
  CalendarDays,
  ChartLine,
  Clock,
  Compass,
  Flame,
  Heart,
  MessageCircle,
  Moon,
  Sparkles,
  Stars,
  Wand2,
} from "lucide-react";

export type EngineField = {
  name: string;
  label: string;
  type: "text" | "email" | "date" | "time" | "select" | "number" | "textarea";
  placeholder?: string;
  options?: string[];
  required?: boolean;
  helper?: string;
};

export type EngineCategory = "Past" | "Current" | "Future";

export type EngineResult = {
  title: string;
  summary: string;
  highlights: Array<{ label: string; value: string }>;
  nextSteps: string[];
};

export type EngineConfig = {
  slug: string;
  title: string;
  description: string;
  cardDescription: string;
  highlight: string;
  category: EngineCategory;
  preview: string[];
  features: string[];
  icon: LucideIcon;
  formTitle: string;
  formDescription: string;
  fields: EngineField[];
  resultTitle: string;
  resultSummary: string;
  resultHighlights: Array<{ label: string; value: string }>;
  nextSteps: string[];
  accent: string;
  cta: string;
};

export const engineConfigs: EngineConfig[] = [
  {
    slug: "horoscope",
    title: "Horoscope",
    description: "Refined natal insights with precise timing and calm guidance.",
    cardDescription: "Birth-chart intelligence that stays crisp and readable.",
    highlight: "Realtime karma map",
    category: "Current",
    preview: ["Chart clarity score", "Dasha timeline peek", "Remedy spotlight"],
    features: ["Birth map", "Dasha focus", "Remedy cues"],
    icon: Moon,
    formTitle: "Build your horoscope profile",
    formDescription: "Capture the essentials for a complete reading.",
    fields: [
      {
        name: "fullName",
        label: "Full name",
        type: "text",
        required: true,
        placeholder: "Your name",
        helper: "Match your official birth records.",
      },
      { name: "birthDate", label: "Birth date", type: "date", required: true, helper: "Select from your birth record." },
      { name: "birthTime", label: "Birth time", type: "time", required: true, helper: "Use 24-hour format." },
      { name: "birthCity", label: "Birth city", type: "text", required: true, placeholder: "City", helper: "Use the city of birth." },
    ],
    resultTitle: "Your core horoscope snapshot",
    resultSummary: "Balanced chart energy with strong lunar emphasis and a supportive Jupiter cycle.",
    resultHighlights: [
      { label: "Ruling themes", value: "Growth, alignment, emotional clarity" },
      { label: "Peak window", value: "12 Aug · 4 Sep" },
      { label: "Support", value: "Meditation · mantra · water rituals" },
    ],
    nextSteps: ["Review your 90-day dasha window", "Lock daily remedies", "Share the profile"],
    accent: "from-indigo-500/30 to-cyan-500/30",
    cta: "Generate horoscope",
  },
  {
    slug: "past-life",
    title: "Past Life",
    description: "Karmic patterns, soul contracts, and restorative focus areas.",
    cardDescription: "A gentle look into karmic memory and release points.",
    highlight: "Soulline stories",
    category: "Past",
    preview: ["Karmic motif scan", "Soul contract hints", "Healing focus map"],
    features: ["Karmic themes", "Soul contracts", "Healing focus"],
    icon: Flame,
    formTitle: "Unlock karmic insights",
    formDescription: "Provide the key timeline anchors for a past-life reading.",
    fields: [
      { name: "fullName", label: "Full name", type: "text", required: true, placeholder: "Your name", helper: "Align with birth records." },
      { name: "birthDate", label: "Birth date", type: "date", required: true, helper: "Use your birth certificate date." },
      {
        name: "focus",
        label: "Current life focus",
        type: "text",
        required: true,
        placeholder: "Relationship, career, health",
        helper: "Share the area you want to explore.",
      },
      { name: "notes", label: "Extra notes", type: "textarea", placeholder: "Share any recurring patterns", helper: "Optional details." },
    ],
    resultTitle: "Past-life narrative focus",
    resultSummary: "A protector role with strong healing vows, now surfacing for closure and balance.",
    resultHighlights: [
      { label: "Recurring motif", value: "Guardian archetype" },
      { label: "Lesson", value: "Releasing control gracefully" },
      { label: "Healing path", value: "Breathwork · water elements" },
    ],
    nextSteps: ["Record a grounding ritual", "Log recurring dreams", "Align with a mentor"],
    accent: "from-orange-500/25 to-pink-500/25",
    cta: "Explore past lives",
  },
  {
    slug: "future",
    title: "Future",
    description: "Forward-looking predictions mapped to cycles and milestones.",
    cardDescription: "Smooth, focused predictions with milestone clarity.",
    highlight: "Long-range forecasts",
    category: "Future",
    preview: ["Milestone radar", "Opportunity scan", "Risk buffer"],
    features: ["Milestones", "Opportunity windows", "Risk alerts"],
    icon: Sparkles,
    formTitle: "Forecast timeline",
    formDescription: "Select your prediction horizon and focus area.",
    fields: [
      { name: "fullName", label: "Full name", type: "text", required: true, placeholder: "Your name", helper: "Match your birth profile." },
      {
        name: "focus",
        label: "Focus area",
        type: "select",
        required: true,
        options: ["Career", "Relationships", "Health", "Finance"],
        helper: "Choose a primary prediction lens.",
      },
      { name: "range", label: "Time range (months)", type: "number", required: true, placeholder: "6", helper: "1 - 24 months." },
      { name: "email", label: "Email", type: "email", required: true, placeholder: "you@example.com", helper: "For report delivery." },
    ],
    resultTitle: "Future outlook",
    resultSummary: "Momentum rises after the second lunar cycle with a strong partnership catalyst.",
    resultHighlights: [
      { label: "Momentum", value: "Rising from Week 6" },
      { label: "Opportunity", value: "Strategic collaboration" },
      { label: "Caution", value: "Guard energy in Week 9" },
    ],
    nextSteps: ["Schedule a strategy review", "Set protective routines", "Capture goals"],
    accent: "from-emerald-500/25 to-sky-500/25",
    cta: "Map the future",
  },
  {
    slug: "matchmaking",
    title: "Matchmaking",
    description: "Compatibility scoring with dosha balance and remedies.",
    cardDescription: "Sharp compatibility scores with clear remedy guidance.",
    highlight: "Dual-profile sync",
    category: "Current",
    preview: ["Compatibility score", "Dosha balance", "Remedy prompts"],
    features: ["Dosha balance", "Partner alignment", "Remedy guide"],
    icon: Heart,
    formTitle: "Partner compatibility",
    formDescription: "Enter both profiles for a precise match score.",
    fields: [
      {
        name: "primaryName",
        label: "Partner A name",
        type: "text",
        required: true,
        placeholder: "Partner A",
        helper: "First person in the match.",
      },
      {
        name: "secondaryName",
        label: "Partner B name",
        type: "text",
        required: true,
        placeholder: "Partner B",
        helper: "Second person in the match.",
      },
      { name: "primaryBirthDate", label: "Partner A birth date", type: "date", required: true, helper: "Birth record date." },
      { name: "secondaryBirthDate", label: "Partner B birth date", type: "date", required: true, helper: "Birth record date." },
    ],
    resultTitle: "Compatibility overview",
    resultSummary: "Strong emotional harmony with a balanced remedy path.",
    resultHighlights: [
      { label: "Compatibility", value: "82 / 100" },
      { label: "Dosha", value: "Mild Mangal focus" },
      { label: "Alignment", value: "Shared values and ritual flow" },
    ],
    nextSteps: ["Review shared rituals", "Book a deeper match reading", "Save the report"],
    accent: "from-rose-500/25 to-fuchsia-500/25",
    cta: "Match two charts",
  },
  {
    slug: "calendar",
    title: "Calendar",
    description: "Śaka calendar highlights, tithi markers, and daily guidance.",
    cardDescription: "Daily alignment with śaka conversions and rituals.",
    highlight: "Śaka converter",
    category: "Current",
    preview: ["Tithi highlights", "Festival cues", "Daily rituals"],
    features: ["Tithi mapping", "Festival highlights", "Daily rituals"],
    icon: CalendarDays,
    formTitle: "Daily alignment",
    formDescription: "Select the day and the type of focus needed.",
    fields: [
      { name: "date", label: "Date", type: "date", required: true, helper: "Pick the day to evaluate." },
      { name: "location", label: "Location", type: "text", required: true, placeholder: "City", helper: "City of ritual." },
      {
        name: "focus",
        label: "Focus",
        type: "select",
        required: true,
        options: ["Career", "Love", "Health", "Spiritual"],
        helper: "Select your intent.",
      },
      { name: "notes", label: "Notes", type: "textarea", placeholder: "Optional intent", helper: "Add context if needed." },
    ],
    resultTitle: "Calendar insight",
    resultSummary: "A restorative tithi with balanced energy for decisive actions.",
    resultHighlights: [
      { label: "Tithi", value: "Shukla Dashami" },
      { label: "Lucky window", value: "08:20 - 10:05" },
      { label: "Recommended", value: "Prayer, planning, new commitments" },
    ],
    nextSteps: ["Add to reminders", "Schedule rituals", "Share the alignment"],
    accent: "from-teal-500/25 to-indigo-500/25",
    cta: "Convert calendar",
  },
  {
    slug: "timeline",
    title: "Timeline",
    description: "Life chapters mapped into a polished timeline view.",
    cardDescription: "Milestone tracking with clear narrative arcs.",
    highlight: "Phases + milestones",
    category: "Future",
    preview: ["Milestone arcs", "Transit checkpoints", "Life chapters"],
    features: ["Life chapters", "Key transits", "Milestone alerts"],
    icon: Clock,
    formTitle: "Timeline mapping",
    formDescription: "Define the timeline horizon and focus.",
    fields: [
      { name: "fullName", label: "Full name", type: "text", required: true, placeholder: "Your name", helper: "Matches birth records." },
      { name: "birthDate", label: "Birth date", type: "date", required: true, helper: "Exact date of birth." },
      { name: "horizon", label: "Horizon (years)", type: "number", required: true, placeholder: "5", helper: "1 - 20 years." },
      {
        name: "focus",
        label: "Focus",
        type: "select",
        required: true,
        options: ["Career", "Family", "Wealth", "Spiritual"],
        helper: "Primary life track.",
      },
    ],
    resultTitle: "Timeline highlights",
    resultSummary: "Two major shifts with a soft landing in the third quarter.",
    resultHighlights: [
      { label: "Major shifts", value: "2" },
      { label: "Primary theme", value: "Expansion & mentorship" },
      { label: "Next checkpoint", value: "Q3 — 12 Oct" },
    ],
    nextSteps: ["Export to calendar", "Set milestone alerts", "Request mentor review"],
    accent: "from-blue-500/25 to-violet-500/25",
    cta: "Load timeline",
  },
  {
    slug: "varshaphal",
    title: "Varshaphal",
    description: "Yearly solar return guidance with refined focus points.",
    cardDescription: "Annual guidance with strong actionable cues.",
    highlight: "Yearly signal",
    category: "Future",
    preview: ["Year tone map", "Quarterly signals", "Priority chart"],
    features: ["Solar return", "Year themes", "Priority chart"],
    icon: Stars,
    formTitle: "Annual chart focus",
    formDescription: "Input the year and personal focus area.",
    fields: [
      { name: "fullName", label: "Full name", type: "text", required: true, placeholder: "Your name", helper: "Use official name." },
      { name: "birthDate", label: "Birth date", type: "date", required: true, helper: "Exact birth date." },
      { name: "year", label: "Year", type: "number", required: true, placeholder: "2025", helper: "Upcoming year." },
      { name: "intent", label: "Intent", type: "text", required: true, placeholder: "Career growth", helper: "Main focus." },
    ],
    resultTitle: "Varshaphal overview",
    resultSummary: "Growth through structured learning and selective collaborations.",
    resultHighlights: [
      { label: "Year tone", value: "Disciplined expansion" },
      { label: "Opportunity", value: "Q2 partnership" },
      { label: "Caution", value: "Energy management" },
    ],
    nextSteps: ["Plan quarterly reviews", "Lock annual rituals", "Share the plan"],
    accent: "from-amber-500/25 to-orange-500/25",
    cta: "View varshaphal",
  },
  {
    slug: "transits",
    title: "Transits",
    description: "Live planetary transits and the cleanest actionable guidance.",
    cardDescription: "Live motion tracking for daily decisions.",
    highlight: "Live transit map",
    category: "Current",
    preview: ["Live transit pulse", "Daily impact cues", "Remedy focus"],
    features: ["Transit alerts", "Daily impact", "Remedy cues"],
    icon: Activity,
    formTitle: "Transit snapshot",
    formDescription: "Capture your location and intent for the transit report.",
    fields: [
      { name: "date", label: "Date", type: "date", required: true, helper: "Select transit date." },
      { name: "location", label: "Location", type: "text", required: true, placeholder: "City", helper: "City for live signals." },
      { name: "intent", label: "Intent", type: "text", required: true, placeholder: "Focus area", helper: "What should we optimize for?" },
      { name: "email", label: "Email", type: "email", required: true, placeholder: "you@example.com", helper: "Send daily digest." },
    ],
    resultTitle: "Transit digest",
    resultSummary: "Strong Mercury alignment favors communication and clear choices.",
    resultHighlights: [
      { label: "Dominant transit", value: "Mercury trine" },
      { label: "Energy", value: "High clarity" },
      { label: "Action", value: "Negotiate and decide" },
    ],
    nextSteps: ["Subscribe to transit alerts", "Plan key meetings", "Save daily snapshot"],
    accent: "from-sky-500/25 to-purple-500/25",
    cta: "Check transits",
  },
  {
    slug: "core-wisdom",
    title: "Core Wisdom",
    description: "Bhrigu Samhita teachings distilled into sharp guidance.",
    cardDescription: "Library-backed answers with ritual direction.",
    highlight: "Eight-section reading",
    category: "Current",
    preview: ["Wisdom snapshot", "Remedy list", "Focus guardrails"],
    features: ["Wisdom archive", "Remedy lists", "Focused guidance"],
    icon: Wand2,
    formTitle: "Ask the wisdom vault",
    formDescription: "Submit the topic and desired depth.",
    fields: [
      { name: "topic", label: "Topic", type: "text", required: true, placeholder: "Career, love, purpose", helper: "Keep it concise." },
      {
        name: "depth",
        label: "Depth",
        type: "select",
        required: true,
        options: ["Quick", "Balanced", "Deep"],
        helper: "How detailed should the response be?",
      },
      { name: "tone", label: "Tone", type: "select", required: true, options: ["Gentle", "Direct", "Structured"], helper: "Pick the style." },
      { name: "notes", label: "Notes", type: "textarea", placeholder: "Optional context", helper: "Share additional context." },
    ],
    resultTitle: "Wisdom response",
    resultSummary: "Focus on disciplined intention and clear communication to unlock steady progress.",
    resultHighlights: [
      { label: "Core message", value: "Alignment through consistency" },
      { label: "Practice", value: "Morning intention ritual" },
      { label: "Avoid", value: "Overcommitting" },
    ],
    nextSteps: ["Save to your vault", "Share with a mentor", "Create reminders"],
    accent: "from-purple-500/25 to-indigo-500/25",
    cta: "Unlock core wisdom",
  },
  {
    slug: "chat",
    title: "Chat",
    description: "Conversational astrology guidance with live context.",
    cardDescription: "Live chat guidance with structured prompts.",
    highlight: "Live counsel",
    category: "Current",
    preview: ["Live prompt", "Context cues", "Follow-up path"],
    features: ["Live answers", "Context-aware", "Follow-up prompts"],
    icon: MessageCircle,
    formTitle: "Start a new chat",
    formDescription: "Set the tone and topic for the conversation.",
    fields: [
      { name: "topic", label: "Topic", type: "text", required: true, placeholder: "Ask a question", helper: "Keep it focused." },
      {
        name: "tone",
        label: "Tone",
        type: "select",
        required: true,
        options: ["Calm", "Direct", "Compassionate"],
        helper: "Choose the conversation style.",
      },
      {
        name: "focus",
        label: "Focus area",
        type: "select",
        required: true,
        options: ["Career", "Love", "Family", "Spiritual"],
        helper: "Primary life area.",
      },
      { name: "email", label: "Email", type: "email", placeholder: "Optional follow-up", helper: "Optional follow-up." },
    ],
    resultTitle: "Chat highlights",
    resultSummary: "You are stepping into a cycle of structured growth with support around relationships.",
    resultHighlights: [
      { label: "Tone", value: "Grounded and supportive" },
      { label: "Priority", value: "Communication clarity" },
      { label: "Next", value: "Ask for a 30-day focus" },
    ],
    nextSteps: ["Open live chat", "Save the prompt", "Share with advisor"],
    accent: "from-cyan-500/25 to-indigo-500/25",
    cta: "Start chat",
  },
  {
    slug: "dashboard",
    title: "Dashboard",
    description: "All engines, alerts, and saved reports in one place.",
    cardDescription: "Mission control for every astrology workflow.",
    highlight: "Progress arcs",
    category: "Current",
    preview: ["Workspace overview", "Recent reports", "Alert readiness"],
    features: ["Recent reports", "Quick actions", "Alerts overview"],
    icon: Compass,
    formTitle: "Personal dashboard setup",
    formDescription: "Update your workspace preferences.",
    fields: [
      { name: "fullName", label: "Name", type: "text", required: true, placeholder: "Your name", helper: "Used in your workspace." },
      {
        name: "timezone",
        label: "Timezone",
        type: "select",
        required: true,
        options: ["IST", "UTC", "EST", "PST"],
        helper: "Align alerts and rituals.",
      },
      { name: "dailyGoal", label: "Daily focus", type: "text", required: true, placeholder: "Clarity, growth", helper: "Daily intention." },
      { name: "email", label: "Email", type: "email", required: true, placeholder: "you@example.com", helper: "Report delivery." },
    ],
    resultTitle: "Dashboard alignment",
    resultSummary: "Your workspace is focused on clarity with daily reminders enabled.",
    resultHighlights: [
      { label: "Next review", value: "Tomorrow · 8:00 AM" },
      { label: "Alerts", value: "3 active" },
      { label: "Saved reports", value: "12" },
    ],
    nextSteps: ["Sync reminders", "Set weekly review", "Invite collaborators"],
    accent: "from-slate-500/25 to-indigo-500/25",
    cta: "Open dashboard",
  },
  {
    slug: "alerts",
    title: "Alerts",
    description: "Transit alerts and daily pings with smart filters.",
    cardDescription: "Precision alerts for transits and milestones.",
    highlight: "Alert feed",
    category: "Current",
    preview: ["Priority filters", "Quiet hour guard", "Signal routing"],
    features: ["Transit pings", "Priority filters", "Quiet hours"],
    icon: Bell,
    formTitle: "Alert settings",
    formDescription: "Tune the frequency and priority levels.",
    fields: [
      {
        name: "priority",
        label: "Priority",
        type: "select",
        required: true,
        options: ["Critical", "Balanced", "Gentle"],
        helper: "Alert intensity level.",
      },
      {
        name: "frequency",
        label: "Frequency",
        type: "select",
        required: true,
        options: ["Real-time", "Daily", "Weekly"],
        helper: "Delivery cadence.",
      },
      { name: "quietHours", label: "Quiet hours", type: "text", required: true, placeholder: "22:00 - 06:00", helper: "Local time." },
      { name: "email", label: "Email", type: "email", required: true, placeholder: "you@example.com", helper: "Primary delivery address." },
    ],
    resultTitle: "Alert signal",
    resultSummary: "Balanced alerts with quiet hours enabled and priority transits highlighted.",
    resultHighlights: [
      { label: "Priority", value: "Balanced" },
      { label: "Next alert", value: "Tonight · 21:10" },
      { label: "Channels", value: "Push, email" },
    ],
    nextSteps: ["Enable push notifications", "Add special dates", "Save alert preset"],
    accent: "from-fuchsia-500/25 to-rose-500/25",
    cta: "View alerts",
  },
  {
    slug: "analytics",
    title: "Analytics",
    description: "Insight dashboards, pattern tracking, and growth metrics.",
    cardDescription: "Performance analytics for your astrological journey.",
    highlight: "Feedback intelligence",
    category: "Current",
    preview: ["Trend snapshots", "Engagement curve", "Goal tracking"],
    features: ["Trend tracking", "Engagement", "Outcome signals"],
    icon: ChartLine,
    formTitle: "Analytics filter",
    formDescription: "Select the window and metric to review.",
    fields: [
      {
        name: "metric",
        label: "Metric",
        type: "select",
        required: true,
        options: ["Engagement", "Milestones", "Consistency", "Remedies"],
        helper: "Choose the dataset.",
      },
      { name: "range", label: "Range", type: "select", required: true, options: ["7 days", "30 days", "90 days"], helper: "Reporting window." },
      { name: "goal", label: "Goal", type: "text", required: true, placeholder: "Focus outcome", helper: "Primary outcome." },
      { name: "email", label: "Email", type: "email", required: true, placeholder: "you@example.com", helper: "Send export." },
    ],
    resultTitle: "Analytics overview",
    resultSummary: "Consistency is rising with a strong focus on remedies this month.",
    resultHighlights: [
      { label: "Engagement", value: "+18%" },
      { label: "Top focus", value: "Remedy adherence" },
      { label: "Next goal", value: "Weekly reflection" },
    ],
    nextSteps: ["Export the report", "Schedule insights review", "Share with advisor"],
    accent: "from-emerald-500/25 to-teal-500/25",
    cta: "Load analytics",
  },
];

export const engineCards = engineConfigs.map((engine) => ({
  slug: engine.slug,
  title: engine.title,
  description: engine.cardDescription,
  category: engine.category,
  preview: engine.preview,
  features: engine.features,
  icon: engine.icon,
  accent: engine.accent,
}));

export const engineBySlug = engineConfigs.reduce<Record<string, EngineConfig>>((acc, engine) => {
  acc[engine.slug] = engine;
  return acc;
}, {});
